name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: thebongy/version-check@v1
        with:
          file: "Cargo.toml"

      - name: Log when unchanged
        if: ${{ steps.check.outputs.versionChanged != 'true' }}
        run: 'echo "No version change :/"'

      - name: Log when changed
        if: ${{ steps.check.outputs.versionChanged == 'true' }}
        run: 'echo "Version change! -> ${{ steps.check.outputs.releaseVersion }}"'

      - name: setup node
        if: ${{ steps.check.outputs.versionChanged == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create Release
        if: ${{ steps.check.outputs.versionChanged != 'true' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.versionChanged }}
          release_name: Release ${{ steps.check.outputs.versionChanged }}
          body: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: publish
        if: ${{ steps.check.outputs.versionChanged == 'true' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build
          npm publish ./pkg
